name: Sync Develop Branch

on:
  push:
    branches:
      - main

jobs:
  sync-develop:
    name: Syncing develop branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: |
          git checkout develop
          git pull origin main
          git push
